name: Deploy to staging
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying application to the staging cluster

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: SSH into server
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H {{ secrets.STAGING_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh -i /home/runner/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.STAGING_IP }} <<'EOF'
            cd ~
            cd app-deploy
            git pull origin main
          EOF