name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying application to the staging cluster

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: SSH into server
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.STAGING_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh -i /home/runner/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.STAGING_IP }} <<'EOF'
            cd ~
            cd app-deploy
            git pull origin main
            cd bash
            bash scripts.sh
            pnpm install
            cd packages/prisma
            npx prisma migrate dev
            cd ../..
            sudo cp nginx-conf/nginx-dev.conf /etc/nginx/nginx.conf
            sudo systemctl restart nginx
            pnpm run build
            cd apps/http-backend
            pm2 restart "http-be" || pm2 start npm --name "http-be" -- start
            cd ../ws-backend
            pm2 restart "ws-be" || pm2 start npm --name "ws-be" -- start
            cd ../web
            pm2 restart "fe" || pm2 start npm --name "fe" -- start
            pm2 restart all
            pm2 save
          EOF