name: Deploy to staging
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying application to the staging cluster

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: SSH into server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ${{ secrets.VM_USERNAME }}@${{ secrets.STAGING_IP }} <<'EOF'
            cd ~
            cd app_deploy
            git pull origin main
          EOF